--
-- Target: Microsoft SQL Server 
-- Syntax: isql /Uuser /Ppassword /Sserver -i\path\filename.sql
-- Date  : May 16 2016 14:40
-- Script Generated by Database Design Studio 2.21.3 
--

--
-- Select Database: 'db_name'
--
 
IF DB_NAME() = 'Grundfos.Database'
    RAISERROR('''Grundfos.Database'' DATABASE CONTEXT NOW IN USE.',1,1)
ELSE
    RAISERROR('ERROR IN BATCH FILE, ''USE db_name'' FAILED!  KILLING THE SPID NOW.',22,127) WITH LOG
 
GO
EXECUTE SP_DBOPTION 'Grundfos.Database' ,'TRUNC. LOG ON CHKPT.' ,'TRUE'
GO
--
-- Drop Table    : 'reading'   
--
DROP TABLE reading
GO
--
-- Drop Table    : 'sensorCharacteristic'   
--
DROP TABLE sensorCharacteristic
GO
--
-- Drop Table    : 'apartmentCharacteristic'   
--
DROP TABLE apartmentCharacteristic
GO
