//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace ECS.Testable
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class StubHeater : IHeater
	{
	    public bool IsWorking { get; set; }

	    public StubHeater(bool isWorking = true)
	    {
	        IsWorking = isWorking;
	    }

        public void TurnOn()
        {
            System.Console.WriteLine("StubHeater is on");
        }

        public void TurnOff()
        {
            System.Console.WriteLine("StubHeater is off");
        }

        public bool RunSelfTest()
        {
            return IsWorking;
        }
    }
}

