//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace ECS.Testable
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class StubTempSensor : ITempSensor
	{
	    public bool IsWorking { get; set; }
        public int CurTemp { get; set; }

	    public StubTempSensor(bool isWorking = true, int curTemp = 0)
	    {
	        IsWorking = isWorking;
	        CurTemp = curTemp;
	    }

        public int GetTemp()
        {
            return CurTemp;
        }

        public bool RunSelfTest()
        {
            return IsWorking;
        }
    }
}

