//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace ECS.Testable
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class TempSensor : ITempSensor
	{
        public int GetTemp()
        {
            return 25;
        }

        public bool RunSelfTest()
        {
            return true;
        }
    }
}

