--
-- Target: Microsoft SQL Server 
-- Syntax: isql /Uuser /Ppassword /Sserver -i\path\filename.sql
-- Date  : Feb 29 2016 12:44
-- Script Generated by Database Design Studio 2.21.3 
--

--
-- Select Database: 'I4DAB_Gruppe2_Handin2'
--
USE I4DAB_Gruppe2_Handin2
GO
 
IF I4DAB_Gruppe2_Handin2() = 'I4DAB_Gruppe2_Handin2'
    RAISERROR('''I4DAB_Gruppe2_Handin2'' DATABASE CONTEXT NOW IN USE.',1,1)
ELSE
    RAISERROR('ERROR IN BATCH FILE, ''USE I4DAB_Gruppe2_Handin2'' FAILED!  KILLING THE SPID NOW.',22,127) WITH LOG
 
GO
EXECUTE SP_DBOPTION 'I4DAB_Gruppe2_Handin2' ,'TRUNC. LOG ON CHKPT.' ,'TRUE'
GO
--
-- Drop Table    : 'Alternativ'   
--
DROP TABLE Alternativ
GO
--
-- Drop Table    : 'Telefon'   
--
DROP TABLE Telefon
GO
--
-- Drop Table    : 'Person'   
--
DROP TABLE Person
GO
--
-- Drop Table    : 'Adresse'   
--
DROP TABLE Adresse
GO