--
-- Target: Microsoft SQL Server 
-- Syntax: isql /Uuser /Ppassword /Sserver -i\path\filename.sql
-- Date  : Feb 29 2016 12:44
-- Script Generated by Database Design Studio 2.21.3 
--


--
-- Select Database: 'db_name'
--
USE I4DAB_Gruppe2_Handin2
GO
 
IF I4DAB_Gruppe2_Handin2() = 'I4DAB_Gruppe2_Handin2'
    RAISERROR('''I4DAB_Gruppe2_Handin2'' DATABASE CONTEXT NOW IN USE.',1,1)
ELSE
    RAISERROR('ERROR IN BATCH FILE, ''USE I4DAB_Gruppe2_Handin2'' FAILED!  KILLING THE SPID NOW.',22,127) WITH LOG
 
GO
EXECUTE SP_DBOPTION 'I4DAB_Gruppe2_Handin2' ,'TRUNC. LOG ON CHKPT.' ,'TRUE'
GO

--
-- Create Table    : 'Adresse'   
-- AdresseID       :  
-- Bynavn          :  
-- Husnummer       :  
-- Postnummer      :  
-- Type            :  
-- Vejnavn         :  
--
CREATE TABLE Adresse (
    AdresseID      BIGINT IDENTITY(1,1) NOT NULL,
    Bynavn         NVARCHAR(500) NOT NULL,
    Husnummer      BIGINT NOT NULL,
    Postnummer     BIGINT NOT NULL,
    Type           NVARCHAR(500) NOT NULL,
    Vejnavn        NVARCHAR(500) NOT NULL,
CONSTRAINT pk_Adresse PRIMARY KEY CLUSTERED (AdresseID))
GO

--
-- Create Table    : 'Person'   
-- PersonID        :  
-- Efternavn       :  
-- Fornavn         :  
-- Mellemnavn      :  
-- Type            :  
-- AdresseID       :  (references Adresse.AdresseID)
--
CREATE TABLE Person (
    PersonID       BIGINT IDENTITY(1,1) NOT NULL,
    Efternavn      NVARCHAR(500) NOT NULL,
    Fornavn        NVARCHAR(500) NOT NULL,
    Mellemnavn     NVARCHAR(500) NOT NULL,
    Type           NVARCHAR(500) NOT NULL,
    AdresseID      BIGINT NOT NULL,
CONSTRAINT pk_Person PRIMARY KEY CLUSTERED (PersonID),
CONSTRAINT fk_Person FOREIGN KEY (AdresseID)
    REFERENCES Adresse (AdresseID)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
GO

--
-- Create Table    : 'Telefon'   
-- TelefonID       :  
-- Nummer          :  
-- Type            :  
-- PersonID        :  (references Person.PersonID)
--
CREATE TABLE Telefon (
    TelefonID      BIGINT IDENTITY(1,1) NOT NULL,
    Nummer         BIGINT NOT NULL,
    Type           NVARCHAR(500) NOT NULL,
    PersonID       BIGINT NOT NULL,
CONSTRAINT pk_Telefon PRIMARY KEY CLUSTERED (TelefonID),
CONSTRAINT fk_Telefon FOREIGN KEY (PersonID)
    REFERENCES Person (PersonID)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
GO

--
-- Create Table    : 'Alternativ'   
-- PersonID        :  (references Person.PersonID)
-- AdresseID       :  (references Adresse.AdresseID)
-- Type            :  
--
CREATE TABLE Alternativ (
    PersonID       BIGINT NOT NULL,
    AdresseID      BIGINT NOT NULL,
    Type           NVARCHAR(500) NOT NULL,
CONSTRAINT pk_Alternativ PRIMARY KEY CLUSTERED (PersonID,AdresseID),
CONSTRAINT fk_Alternativ FOREIGN KEY (PersonID)
    REFERENCES Person (PersonID)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
CONSTRAINT fk_Alternativ2 FOREIGN KEY (AdresseID)
    REFERENCES Adresse (AdresseID)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
GO

--
-- Permissions for: 'public'
--
GRANT ALL ON Adresse TO public
GO
GRANT ALL ON Person TO public
GO
GRANT ALL ON Telefon TO public
GO
GRANT ALL ON Alternativ TO public
GO